# Generated by Django 4.0.2 on 2022-04-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_pin_point_topic_rename_subject_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
