# Generated by Django 4.0.2 on 2022-04-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_benefit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='inputs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=200)),
                ('word', models.CharField(max_length=200)),
            ],
        ),
    ]
